export const actions={
    GET_ALL_CLINICIANS:'GET_ALL_CLINICIANS',
    GET_CLINICIANS_WITH_FILTER:'GET_CLINICIANS_WITH_FILTER',
    ADD_NEW_CLINICIAN:'ADD_NEW_CLINICIAN',
    DELETE_CLINICIAN:'DELETE_CLINICIAN'
}